# Generated by Django 5.0 on 2024-01-04 13:09

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_content',
            name='Blog_content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
